services:
  backend:
    image: backend
    build:
      dockerfile: backend/backend.Dockerfile
    volumes:
      - ./backend/src:/app
      - ./backend/db:/app/db
  frontend:
    image: frontend
    build:
      dockerfile: frontend/frontend.Dockerfile
