services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
      - ./backend/db:/app/db
    command: fastapi dev main.py --host 0.0.0.0 --port 8000

