services:
  backend:
    image: backend
    build:
      dockerfile: backend/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
      - ./backend/db:/app/db
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
  frontend:
    image: frontend
    build:
      dockerfile: frontend/frontend.Dockerfile
  reverse-proxy:
    image: reverse-proxy
    build:
      dockerfile: reverse-proxy/reverse-proxy.Dockerfile
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./reverse-proxy/data:/data
      - ./reverse-proxy/letsencrypt:/etc/letsencrypt
