restaurant_names=[
    "Pizza Planet",
    "Burger Craft",
    "Noodle Nook",
    "Wrap Empire",
    "Sushi Wave",
    "Grilltopia",
    "Curry Leaf",
    "Taco Tango",
    "Urban Spoon",
    "Kimchi Kitchen",
    "Hot Pot Express",
    "Dragon Bowl",
    "Frytomania",
    "Trattoria Luna",
    "Wok & Roll",
    "Spaghetti Bros",
    "Zupa i Spółka",
    "Mega Kebab",
    "Chopstick City",
    "KuraBar",
    "Pho for Real",
    "Zapiekankarnia",
    "Bistro Bulion",
    "Pierogarnia Królowa",
    "Ramen Raiders",
    "Steak Street",
    "Tostownia",
    "Makaroniarnia Viva",
    "Green Fork",
    "Obiady Domowe U Krysi",
    "Donut Republic",
    "Veggie Vibes",
    "Miseczka Szczęścia",
    "Grubo Mielone",
    "Pastificio Roma",
    "Kebabistan",
    "Buła i Spółka",
    "Burgerówka",
    "Sajgon Express",
    "Patelnia u Zenka",
    "BentoBox",
    "Pizza Tytan",
    "Leśna Kuchnia",
    "Bun Factory",
    "Chili Zone",
    "Włoski Zakątek",
    "Królewski Kebab",
    "Raviolo",
    "Kura Express",
    "Sosik Bar",
    "StreetFoodowy",
    "Talerz Pełen",
    "Tatar&More",
    "Focaccia Club",
    "Zielona Miska",
    "Ogniem i Patelnią",
    "Wrapido",
    "Bistro Warszawska",
    "Bakłażanowy Raj",
    "Pulled Pork King",
    "Tajskie Historie",
    "Bistro Bambus",
    "Zupa Dnia",
    "Bułka Zeszła",
    "U Dziadka",
    "Bar Mleczny Alfa",
    "Food Truck Empire",
    "Manhattan Kebab",
    "Sosny Bistro",
    "Pasta Machina",
    "Asia Mix",
    "Bigos Brothers",
    "Yum Yum Town",
    "Burgery u Stacha",
    "Niebo w Gębie",
    "Zapiekanki 2000",
    "Domowe Przysmaki",
    "Pikantna Misja",
    "Falafel Garden",
    "Kurczak Pieczony",
    "Makaronowe Love",
    "Łosoś i Przyjaciele",
    "U Frytki",
    "Kluseczka",
    "Mięcho Mix",
    "U Babci Heli",
    "Foodzona",
    "Spoko Zupa",
    "Złoty Wok",
    "Między Bułkami",
    "Ramenarnia",
    "Kebabowy Patrol",
    "Sushi Love",
    "Bistro Wakame",
    "Makaroniarnia Pastella",
    "Frytki na Miarę",
    "Sosik i Klusik",
    "Pizza Express",
    "U Pana Kotleta",
    "Urban Curry",
    "Fit na Talerzu",
    "Gołąbki Deluxe",
    "Hot Wraps",
    "Szama Bar",
    "Sałatownia",
    "U Głodnego Wilka",
    "Bread & Bowl",
    "Meatball House",
    "Kura Na Wypasie",
    "Domowy Catering",
    "Rosół i Spółka",
    "Riksha Taste",
    "Plackarnia",
    "Kawiarnia U Stefanii",
    "Bajgiel Bistro",
    "Wraps & Co",
    "Skład Kanapkowy",
    "Fusion Taste",
    "Pasibus",
    "Pan Sushi",
    "Miso Master",
    "Karczma u Jana",
    "Słony Pomidor",
    "Kuchnia Pod Blokiem",
    "Buła & Mielone",
    "Pulled Bar",
    "Patelniowa",
    "Asia Bistro",
    "Pastacraft",
    "Miski z Misją",
    "Ramen Express",
    "Kurczak z Rynku",
    "Zielony Talerz",
    "Bułka w Ogień",
    "Przystanek Smak",
    "U Głodnego",
    "Food Station",
    "Bagietka & Spółka",
    "Domowe z Widelcem",
    "Zupa Love",
    "Na Ruchu",
    "Pasta i Basta",
    "Jemy Tu",
    "Talerz u Jacka",
    "Street Wok",
    "Tatar Bar",
    "Mięsny Punkt",
    "Kebab Express",
    "Sztuka Jedzenia",
    "Bar Pod Rynkiem",
    "Wypasiona Miska",
    "U Pieczonego",
    "Pierożek z Duszą"
]
