food = [
    "pizza",
    "sushi",
    "tacos",
    "paella",
    "pierogi",
    "kimchi",
    "hamburger",
    "falafel",
    "kebab",
    "curry",
    "churros",
    "ramen",
    "gyros",
    "gnocchi",
    "ceviche",
    "biryani",
    "musaka",
    "tapas",
    "risotto",
    "gulasz",
    "quiche",
    "tempura",
    "pho",
    "dumplings",
    "samosa",
    "banh mi",
    "cassoulet",
    "empanadas",
    "shawarma",
    "bibimbap",
    "okonomiyaki",
    "jollof",
    "baklava",
    "fondue",
    "laksa",
    "satay",
    "raclette",
    "arepas",
    "borszcz",
    "hummus",
    "tortilla",
    "naan",
    "kroket",
    "pelmeni",
    "poutine",
    "fufu",
    "sauerbraten",
    "tamale",
    "mole",
    "mochi",
    "zrazy",
    "karē",
    "knedle",
    "makaroniki",
    "strudel",
    "adzuki",
    "bobotie",
    "katsu",
    "khachapuri",
    "pljeskavica",
    "crêpe",
    "kibbeh",
    "tagine",
    "kulfi",
    "onigiri",
    "manti",
    "pastel de nata",
    "schnitzel",
    "börek",
    "shakshuka",
    "khash",
    "pavlova",
    "gulab jamun",
    "miso",
    "roti",
    "sai krok",
    "tahini",
    "gravadlax",
    "luomo",
    "babka",
    "tarte tatin",
    "fish and chips",
    "cassava",
    "lángos",
    "tamarindo",
    "matoke",
    "chashu",
    "arancini",
    "yassa",
    "ajvar",
    "zupa miso",
    "korma",
    "meze",
    "dim sum",
    "masala dosa",
    "pączki",
    "oscypek",
    "halva",
    "couscous",
    "pide"
]
