vehicle_names=[
    "EcoRider 200",
    "Zipster Pro",
    "VoltCycle X",
    "CargoBug 3",
    "Urban Dash",
    "SwiftGo Mini",
    "Flywheel S2",
    "ZenoScoot",
    "FlashRider Z",
    "HyperBike 7",
    "CourierJet 1",
    "SpinCruze",
    "QuickHaul V",
    "SnapMove 4X",
    "BuzzRoller",
    "Greendash Neo",
    "StormScoot",
    "RunnerX Light",
    "ZipMoto Flex",
    "DashQuadro",
    "TurboTrek 88",
    "MiniHustle",
    "MetroSprint",
    "ZoomMax C",
    "VelociGo 3",
    "GlideRover",
    "FoodRush Pro",
    "EazyCruze 5",
    "NimbleBuggy",
    "RapidRunner"
]
