cities=[
    "Warszawa",
    "Kraków",
    "Łódź",
    "Wrocław",
    "Poznań",
    "Gdańsk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Białystok",
    "Katowice",
    "Gdynia",
    "Częstochowa",
    "Radom",
    "Toruń",
    "Sosnowiec",
    "Kielce",
    "Rzeszów",
    "Ruda Śląska",
    "Zabrze",
    "Nowy Sącz",
    "Tychy",
    "Dąbrowa Górnicza",
    "Opole",
    "Elbląg",
    "Płock",
    "Wałbrzych",
    "Włocławek",
    "Tarnów",
    "Chorzów",
    "Kalisz",
    "Koszalin",
    "Legnica",
    "Grudziądz",
    "Słupsk",
    "Jaworzno",
    "Jastrzębie-Zdrój",
    "Nowy Targ",
    "Olsztyn",
    "Zamość"
]

